<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\core\RagnaModManager.Core\RagnaModManager.Core.csproj" />
    <ProjectReference Include="..\..\ragnarock\RagnaModManager.Ragnarock\RagnaModManager.Ragnarock.csproj" />
    <ProjectReference Include="..\..\platform\RagnaModManager.Platform\RagnaModManager.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.*" />
    <PackageReference Include="Avalonia.Desktop" Version="11.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.*" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.*" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>RagnaModManager</AssemblyName>
    <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
